In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\new\anaconda3\lib\site-packages (1.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\new\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\new\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\new\anaconda3\lib\site-packages (from pandas) (1.20.3)
Requirement already satisfied: six>=1.5 in c:\users\new\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('pitches.csv', usecols=['ab_id','pitch_type','code','type','b_count','s_count','outs','on_1b','on_2b','on_3b','px','pz','zone','start_speed','end_speed'])
df

,px,pz,start_speed,end_speed,zone,code,type,pitch_type,ab_id,b_count,s_count,outs,on_1b,on_2b,on_3b
0,0.416,2.963,92.9,84.1,3.0,C,S,FF,2015000001,0,0,0,0,0,0
1,-0.191,2.347,92.8,84.1,5.0,S,S,FF,2015000001,0,1,0,0,0,0
2,-0.518,3.284,94.1,85.2,1.0,F,S,FF,2015000001,0,2,0,0,0,0
3,-0.641,1.221,91.0,84.0,13.0,B,B,FF,2015000001,0,2,0,0,0,0
4,-1.821,2.083,75.4,69.6,13.0,B,B,CU,2015000001,1,2,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,-0.777,1.301,73.5,68.4,13.0,B,B,KN,2016089829,2,2,1,0,0,0
1048571,-0.276,1.986,78.1,72.0,7.0,X,X,KN,2016089829,3,2,1,0,0,0
1048572,-0.127,4.070,79.0,73.6,11.0,B,B,KN,2016089830,0,0,2,0,0,0
1048573,0.163,3.084,71.6,66.5,2.0,C,S,KN,2016089830,1,0,2,0,0,0
1048574,-0.625,2.864,66.4,61.6,1.0,C,S,EP,2016089830,1,1,2,0,0,0

In [4]:
df.count()

px             1047019
pz             1047019
start_speed    1047028
end_speed      1047028
zone           1047019
code           1042856
type           1048575
pitch_type     1047019
ab_id          1048575
b_count        1048575
s_count        1048575
outs           1048575
on_1b          1048575
on_2b          1048575
on_3b          1048575
dtype: int64

In [5]:
pitches_df = df.dropna()

In [6]:
pitches_df.count()

px             1041304
pz             1041304
start_speed    1041304
end_speed      1041304
zone           1041304
code           1041304
type           1041304
pitch_type     1041304
ab_id          1041304
b_count        1041304
s_count        1041304
outs           1041304
on_1b          1041304
on_2b          1041304
on_3b          1041304
dtype: int64

In [7]:
pitches_df = pitches_df[['ab_id','pitch_type','code','type','b_count','s_count','outs','on_1b','on_2b','on_3b','px','pz','zone','start_speed','end_speed']]

In [8]:
pitches_df.dtypes

ab_id            int64
pitch_type      object
code            object
type            object
b_count          int64
s_count          int64
outs             int64
on_1b            int64
on_2b            int64
on_3b            int64
px             float64
pz             float64
zone           float64
start_speed    float64
end_speed      float64
dtype: object

In [9]:
pitches_type_df = pd.get_dummies(pitches_df[['pitch_type']])

In [10]:
pitches_type_df.head(15)

,pitch_type_AB,pitch_type_CH,pitch_type_CU,pitch_type_EP,pitch_type_FA,pitch_type_FC,pitch_type_FF,pitch_type_FO,pitch_type_FS,pitch_type_FT,pitch_type_IN,pitch_type_KC,pitch_type_KN,pitch_type_PO,pitch_type_SC,pitch_type_SI,pitch_type_SL,pitch_type_UN
0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
12,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
13,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

In [11]:
baseball_df = pd.merge(pitches_type_df, pitches_df, left_index = True, right_index = True)
baseball_df.head()

,pitch_type_AB,pitch_type_CH,pitch_type_CU,pitch_type_EP,pitch_type_FA,pitch_type_FC,pitch_type_FF,pitch_type_FO,pitch_type_FS,pitch_type_FT,...,s_count,outs,on_1b,on_2b,on_3b,px,pz,zone,start_speed,end_speed
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0.416,2.963,3.0,92.9,84.1
1,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,-0.191,2.347,5.0,92.8,84.1
2,0,0,0,0,0,0,1,0,0,0,...,2,0,0,0,0,-0.518,3.284,1.0,94.1,85.2
3,0,0,0,0,0,0,1,0,0,0,...,2,0,0,0,0,-0.641,1.221,13.0,91.0,84.0
4,0,0,1,0,0,0,0,0,0,0,...,2,0,0,0,0,-1.821,2.083,13.0,75.4,69.6

In [12]:
baseball_df = baseball_df[['ab_id','pitch_type_AB', 'pitch_type_CH', 'pitch_type_CU', 'pitch_type_EP', 'pitch_type_FA', 'pitch_type_FC', 'pitch_type_FF', 'pitch_type_FO', 'pitch_type_FS', 'pitch_type_FT', 'pitch_type_IN', 'pitch_type_KC', 'pitch_type_KN', 'pitch_type_PO', 'pitch_type_SC', 'pitch_type_SI', 'pitch_type_SL', 'pitch_type_UN', 'pitch_type','code','type','b_count','s_count','outs','on_1b','on_2b','on_3b','px','pz','zone','start_speed','end_speed']]
baseball_df.head()

,ab_id,pitch_type_AB,pitch_type_CH,pitch_type_CU,pitch_type_EP,pitch_type_FA,pitch_type_FC,pitch_type_FF,pitch_type_FO,pitch_type_FS,...,s_count,outs,on_1b,on_2b,on_3b,px,pz,zone,start_speed,end_speed
0,2015000001,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0.416,2.963,3.0,92.9,84.1
1,2015000001,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,-0.191,2.347,5.0,92.8,84.1
2,2015000001,0,0,0,0,0,0,1,0,0,...,2,0,0,0,0,-0.518,3.284,1.0,94.1,85.2
3,2015000001,0,0,0,0,0,0,1,0,0,...,2,0,0,0,0,-0.641,1.221,13.0,91.0,84.0
4,2015000001,0,0,1,0,0,0,0,0,0,...,2,0,0,0,0,-1.821,2.083,13.0,75.4,69.6

In [14]:
baseball_df.to_csv (r'C:\Users\New\Desktop\BootcampUA\Final Project\filtered_pitches.csv', index = False, header=True)

print (baseball_df)

              ab_id  pitch_type_AB  pitch_type_CH  pitch_type_CU  \
0        2015000001              0              0              0
1        2015000001              0              0              0
2        2015000001              0              0              0
3        2015000001              0              0              0
4        2015000001              0              0              1
...             ...            ...            ...            ...
1048570  2016089829              0              0              0
1048571  2016089829              0              0              0
1048572  2016089830              0              0              0
1048573  2016089830              0              0              0
1048574  2016089830              0              0              0

         pitch_type_EP  pitch_type_FA  pitch_type_FC  pitch_type_FF  \
0                    0              0              0              1
1                    0              0              0              1
2                    0              0              0              1
3                    0              0              0              1
4                    0              0              0              0
...                ...            ...            ...            ...
1048570              0              0              0              0
1048571              0              0              0              0
1048572              0              0              0              0
1048573              0              0              0              0
1048574              1              0              0              0

         pitch_type_FO  pitch_type_FS  ...  s_count  outs  on_1b  on_2b  \
0                    0              0  ...        0     0      0      0
1                    0              0  ...        1     0      0      0
2                    0              0  ...        2     0      0      0
3                    0              0  ...        2     0      0      0
4                    0              0  ...        2     0      0      0
...                ...            ...  ...      ...   ...    ...    ...
1048570              0              0  ...        2     1      0      0
1048571              0              0  ...        2     1      0      0
1048572              0              0  ...        0     2      0      0
1048573              0              0  ...        0     2      0      0
1048574              0              0  ...        1     2      0      0

         on_3b     px     pz  zone  start_speed end_speed
0            0  0.416  2.963   3.0         92.9      84.1
1            0 -0.191  2.347   5.0         92.8      84.1
2            0 -0.518  3.284   1.0         94.1      85.2
3            0 -0.641  1.221  13.0         91.0      84.0
4            0 -1.821  2.083  13.0         75.4      69.6
...        ...    ...    ...   ...          ...       ...
1048570      0 -0.777  1.301  13.0         73.5      68.4
1048571      0 -0.276  1.986   7.0         78.1      72.0
1048572      0 -0.127  4.070  11.0         79.0      73.6
1048573      0  0.163  3.084   2.0         71.6      66.5
1048574      0 -0.625  2.864   1.0         66.4      61.6

[1041304 rows x 33 columns]